version = 0.1
[snatarajan]
[snatarajan.deploy]
[snatarajan.deploy.parameters]
stack_name = "testJenkins"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ilealyxm5gpb"
s3_prefix = "testJenkins"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
